services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"      # Default MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  app:
    build: .
    depends_on:
      - mosquitto
    env_file:
      - .env
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
  
